# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: bookstore
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432
